POST http://127.0.0.1:8000/api/users
Content-Type: application/json
Authorization: Bearer 81|TquVmewiKvUrDqkCs8OXVswxD5gMe2DbL4zHKzrS3a68de84

{
    "name": "John Doe ert3tert1111",
    "email": "john.doe@example.com",
    "password": "securepassword",
    "image": "base64EncodedImageString"
}
